### ISSUE TITLE
Automate Org Exports With Deploy Script

### ISSUE THREAD

**Issue by jgkamat** [jgkamat/jgkamat.github.io#3]
https://lists.gnu.org/archive/html/emacs-orgmode/2011-04/msg00220.html

It seems like I can generate the HTML via some automation, I just need to set that up. Shouldn't be too hard :smile:

**Comment by jgkamat** [comment]
This has been completed, and is live now! Sources are built on the sources branch, to the master branch (where they reflect the live instance).

**Comment by Ambrevar** [comment]
Can you explain how this works?

**Comment by jgkamat** [comment]
Yup, it's a bit hacky to get it to work on github (gitlab is a bit easier, but I'm already on github hosting for now...)

Right now, there's two branches here, [master](https://github.com/jgkamat/jgkamat.github.io/tree/master), and [sources](https://github.com/jgkamat/jgkamat.github.io/tree/sources). Master corresponds to the hosted version (it's forced to be named master), while 'sources' is the branch I actually commit to.

Every time I push an update to the sources branch, [it gets built by circleci](https://circleci.com/gh/jgkamat/jgkamat.github.io), using the [jgkamat-publish function here](https://github.com/jgkamat/jgkamat.github.io/blob/eea9d92f0cb79e5514d8e7efc99d656592289285/jgkamat-website.el#L161). This generates html files that correspond to the org source files.

Then, I clone a copy of this repo on the master branch (in ci) to a 'html' subdir, copy the resulting files into that sub-repo, commit and push to master. [The config for the pushing is here in a circle.yml](https://github.com/jgkamat/jgkamat.github.io/blob/sources/.circleci/config.yml). In order to get push permissions, I had to add a github token environment token to my CI builds (which isn't exposed on fork builds, to be safe).

Gitlab is actually a lot nicer with this, [and lets you just designate an output dir of your repo to become the root of your public website](https://gitlab.com/jgkamat/schedules/blob/master/.gitlab-ci.yml), rather than forcing you to either use jekyll or use some CI automation to do this.

Let me know if you have any other questions, I'm always happy to answer them :D

**Comment by Ambrevar** [comment]
Thank you very much for this extensive answer! :)
Indeed, Gitlab seems a lot simpler in that area.

Great job with your website by the way!

**Comment by Ambrevar** [comment]
By the way, if your main concern is to stick to a stable URL for your homepage, why not going for a personal domain name?  Then you could freely switch from one host to another (e.g. GitLab before the next better alternative shows up).

**Comment by jgkamat** [comment]
Mainly the only reason I don't do a personal domain is that I'm too cheap to get one at the moment :).

Eventually I do plan to set up a real domain, but I wanted the source to be on github for better visibility for now. Maybe I'll use gitlab mirroring to mirror this instance, and then build and host on gitlab. It is on the long-term list of things I want to do though :)

**Comment by jgkamat** [comment]
I just wanted to update this saying that I've done this (to assist moving all my personal repos over to gitlab). The new site has code at https://gitlab.com/jgkamat/jgkamat.gitlab.io and is hosted at http://jgkamat.gitlab.io/. I can also trick github into serving 301s to the new address via "custom domains" so I think I should be able to migrate transparently. I just need to verify everything is working exactly the same and the migration should be complete (and I can turn this repo into a stub).
